-- MySQL Script generated by MySQL Workbench
-- qua 29 mai 2019 20:37:02 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `DB_campeonato` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_time` (
  `nmSigla` VARCHAR(4) NOT NULL,
  `nmNome` VARCHAR(128) NOT NULL,
  `dtFundacao` VARCHAR(12) NOT NULL,
  `nmPresidente` VARCHAR(256) NOT NULL,
  `nmVice` VARCHAR(256) NOT NULL,
  `numPontos` INT NOT NULL,
  PRIMARY KEY (`nmSigla`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`TB_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_partida` (
  `dtPartida` VARCHAR(12) NOT NULL,
  `dsLocal` VARCHAR(128) NOT NULL,
  `dsLocalCidade` VARCHAR(256) NOT NULL,
  `numGolsVisitante` INT NOT NULL,
  `numGolsCasa` INT NOT NULL,
  `dsLocalUfEstado` VARCHAR(4) NOT NULL,
  `nmVisitanteSigla` VARCHAR(4) NOT NULL,
  `nmCasaSigla` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`nmCasaSigla`, `nmVisitanteSigla`),
  FOREIGN KEY (`nmVisitanteSigla`)
  REFERENCES `TB_time` (`nmSigla`),
  FOREIGN KEY (`nmCasaSigla`)
  REFERENCES `TB_time` (`nmSigla`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

DROP TABLE `TB_time`;
DROP TABLE `TB_partida`;
TRUNCATE TABLE `TB_time`;
TRUNCATE TABLE `TB_partida`;
SELECT * FROM `TB_partida`;
DELETE FROM `TB_time` WHERE nmSigla = "VAS";

SELECT tt.nmSigla, tt.nmNome, tt.nmPresidente, tt.nmVice, tt.dtFundacao, tt.numPontos FROM TB_time AS tt
UNION ALL
tp.dtPartida, tp.dsLocal, tp.dsLocalCidade, tp.numGolsVisitante, tp.numGolsCasa, tp.dsLocalUfEstado, tp.nmVisitanteSigla , tp.nmCasaSigla FROM TB_partida AS tp;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SELECT tt.nmSigla, tt.nmNome, tt.nmPresidente, tt.nmVice, tt.dtFundacao, tt.numPontos FROM TB_time AS tt JOIN TB_partida AS tp;

SELECT * FROM TB_time, TB_partida;

SELECT p.nmCasaSigla, p.nmVisitanteSigla FROM TB_partida AS p
JOIN
TB_time AS t ON p.nmCasaSigla = t.nmSigla OR p.nmVisitanteSigla = t.nmSigla
WHERE t.nmSigla = "FLU";
